### ISSUE TITLE
Add OMERO to licensing page

### ISSUE THREAD

**Issue by manics** [ome/www.openmicroscopy.org#348]
It's currently missing from https://www.openmicroscopy.org/licensing/

**Comment by pwalczysko** [comment]
Happy to format it and open a PR, but what content should be in the blurb ? cc @manics @sbesson

**Comment by joshmoore** [comment]
Much the same as the Bio-Formats section but without the sentences about readers ("some components which provide reader and writer implementations for open file formats, are released under a more permissive BSD-2 license which enables non-GPL third party software. For a complete list of which file formats are included in the BSD license, see the BSD column of the supported formats table. ")

**Comment by pwalczysko** [comment]
Opened https://github.com/ome/www.openmicroscopy.org/pull/431

**Comment by manics** [comment]
Closed by https://github.com/ome/www.openmicroscopy.org/pull/431
