### ISSUE TITLE
Website is down?

### ISSUE THREAD

**Issue by raivivek** [ome/www.openmicroscopy.org#416]
Hi — I'm wondering if the website is currently down? I'm unable to load any of the pages under the `openmicroscopy.org` domain. What can I do to fix it?

See [isitdownrightnow.com](https://www.isitdownrightnow.com/openmicroscopy.org.html) or [currentlydown](http://currentlydown.com/www.openmicroscopy.org).

**Comment by jburel** [comment]
Hi @raivivek 
We are dealing with all our University of Dundee systems including all our testing infrastructure being down following a power outage so please bear with us.

**Comment by joshmoore** [comment]
see also: https://forum.image.sc/t/ome-resources-down-due-to-uod-outage/43957

**Comment by sbesson** [comment]
A subset of the website is now available via GitHub pages although we are still recovering from the outage. Closing this.
