### ISSUE TITLE
Clearer "Getting started with OMERO" page

### ISSUE THREAD

**Issue by joshmoore** [ome/www.openmicroscopy.org#454]
The goal is to have a single URL that we can hand to facilities and institutes that are interested in implementing an OMERO server. Current candidate is:

* https://www.openmicroscopy.org/omero/institution/getting-started.html

(perhaps with an alias)

## Justification
* What's needed to host OMERO?
* How many people and what type of roles?
* What are the cost savings?
* Perhaps reports from others?

## General overview of the documentation
* http://omero-guides.readthedocs.io/
* etc.

## Getting in touch
* https://image.sc/tags/omero (maybe a "newbie" tag?)
* https://www.openmicroscopy.org/training/
* Yearly meeting
* Regional groups: Germany's RDM4mic, "list your group here"

**Comment by pwalczysko** [comment]
Fixed by https://github.com/ome/www.openmicroscopy.org/pull/462
