### ISSUE TITLE
scls links are now 403

### ISSUE THREAD

**Issue by joshmoore** [ome/www.openmicroscopy.org#601]
*  External link https://www.softwarecollections.org/en/scls/rhscl/devtoolset-3/ failed: 403 No error
  *  External link https://www.softwarecollections.org/en/scls/rhscl/devtoolset-4/ failed: 403 No error

**Comment by joshmoore** [comment]
see https://github.com/ome/www.openmicroscopy.org/pull/599#issuecomment-1189302574

**Comment by sbesson** [comment]
The broken links to have been fixed upstream.
