### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by junelsolis** [ome/www.openmicroscopy.org#754]
Hello. The website is seems to be down and inaccessible from Finland for at least three hours now.

**Comment by pwalczysko** [comment]
@junelsolis  Thank you for the report. Unfortunately, some of the hardware underlying the website developed a  fault during this weekend. We are working on it in cooperation with our provider University of Dundee IT and Dell. Please see https://forum.image.sc/t/ome-system-down/101981/2

**Comment by pwalczysko** [comment]
Thank you again @junelsolis , also for the quick noticing that the site is accessible now again.

**Comment by junelsolis** [comment]
Thanks for fixing the website, and in a larger sense, OMERO and Bio-Formats :)
